name: Deploy GH Pages (Frontend Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Compute BASE_PATH from repo
        run: echo "BASE_PATH=/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build static export for GH Pages
        env:
          NEXT_PUBLIC_DEPLOY_TARGET: gh-pages
          NEXT_PUBLIC_BASE_PATH: ${{ env.BASE_PATH }}
          NEXT_PUBLIC_API_BASE: ${{ secrets.API_BASE_URL }}
        run: |
          npm run build
          npx next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true

